from __future__ import annotations

import pathlib

from multica_py.enums import IssueStatus, ProjectStatus
from multica_py.models.agents import AgentCreateRequest, AgentUpdateRequest
from multica_py.models.issues import (
    IssueAssignmentRequest,
    IssueCreateRequest,
    IssueReorderRequest,
    IssueUpdateRequest,
)
from multica_py.models.project_resources import (
    ProjectResourceAddLocalDirectoryRequest,
    ProjectResourceUpdateLocalDirectoryRequest,
)
from multica_py.models.projects import ProjectCreateRequest, ProjectUpdateRequest
from multica_py.models.skills import SkillCreateRequest, SkillUpdateRequest
from multica_py.models.system import AttachmentResult
from tests.component.resource_payloads import *  # noqa: F403
from tests.component.resource_support import C, CommandCase

# ruff: noqa: F405

_PR_LOCAL_DIR = str(pathlib.Path("/tmp/sandbox").resolve())

# fmt: off
SUCCESS_COMMAND_CASES: tuple[CommandCase, ...] = (
    C('agents.list', 'agents.list', invoke=lambda c: c.agents.list(), expected_argv=('agent', 'list', '--output', 'json'), stdout=P_ID_AG_001_NAME_HELPER_SKILLS, check='nonempty'),
    C('agents.archive', 'agents.archive', invoke=lambda c: c.agents.archive("ag_001"), expected_argv=('agent', 'archive', 'ag_001'), check='none'),
    C('agents.create', 'agents.create', invoke=lambda c: c.agents.create(AgentCreateRequest(name="Helper")), expected_argv=('agent', 'create', '--name', 'Helper', '--output', 'json'), stdout=P_ID_AG_001_NAME_HELPER_SKILLS_2),
    C('agents.get', 'agents.get', invoke=lambda c: c.agents.get("ag_001"), expected_argv=('agent', 'get', 'ag_001', '--output', 'json'), stdout=P_ID_AG_001_NAME_HELPER_SKILLS_2),
    C('agents.restore', 'agents.restore', invoke=lambda c: c.agents.restore("ag_001"), expected_argv=('agent', 'restore', 'ag_001'), check='none'),
    C('agents.skills.list', 'agents.skills.list', invoke=lambda c: c.agents.skills.list("ag_001"), expected_argv=('agent', 'skill', 'list', 'ag_001', '--output', 'json'), stdout=P_ID_SK_001_NAME_SKILL, check='nonempty'),
    C('agents.skills.set', 'agents.skills.set', invoke=lambda c: c.agents.skills.set("ag_001", ("sk_001",)), expected_argv=('agent', 'skill', 'set', 'ag_001', '--skill-id', 'sk_001'), check='none'),
    C('agents.tasks', 'agents.tasks', invoke=lambda c: c.agents.tasks("ag_001"), expected_argv=('agent', 'tasks', 'ag_001', '--output', 'json'), stdout=P_ID_TASK_001_STATUS_DONE_ISSUE, check='nonempty'),
    C('agents.update', 'agents.update', invoke=lambda c: c.agents.update("ag_001", AgentUpdateRequest(name="Helper")), expected_argv=('agent', 'update', 'ag_001', '--name', 'Helper', '--output', 'json'), stdout=P_ID_AG_001_NAME_HELPER_SKILLS_2),
    C('agents.upload_avatar', 'agents.upload_avatar', invoke=lambda c: c.agents.upload_avatar("ag_001", "/tmp/avatar.png"), expected_argv=('agent', 'avatar', 'upload', 'ag_001', '--image', '/private/tmp/avatar.png'), check='none'),
    C('attachments.list.all', 'attachments.list', invoke=lambda c: c.attachments._run_json_decode_list(("attachment", "list"), AttachmentResult), expected_argv=('attachment', 'list', '--output', 'json'), stdout=P_ID_AT_001_FILENAME_FILE_TXT_U, check='nonempty'),
    C('attachments.list.iss_001', 'attachments.list', invoke=lambda c: c.attachments.list("iss_001"), expected_argv=('attachment', 'list', 'iss_001', '--output', 'json'), stdout=P_ID_AT_001_FILENAME_FILE_TXT_U, check='nonempty'),
    C('attachments.upload', 'attachments.upload', invoke=lambda c: c.attachments.upload("iss_001", "/tmp/file.txt"), expected_argv=('attachment', 'upload', 'iss_001', '--file', '/private/tmp/file.txt', '--output', 'json'), stdout=P_ID_ATT_001_FILENAME_FILE_TXT),
    C('attachments.download', 'attachments.download', invoke=lambda c: c.attachments.download("att_001", "/tmp/out.txt"), expected_argv=('attachment', 'download', 'att_001', '--output', '/private/tmp/out.txt'), check='none'),
    C('auth.login', 'auth.login', invoke=lambda c: c.auth.login("secret-token"), expected_argv=('auth', 'login', '--token', 'secret-token'), stdout=P_LOGIN_SUCCESSFUL, check='auth_login'),
    C('auth.status', 'auth.status', invoke=lambda c: c.auth.status(), expected_argv=('auth', 'status', '--output', 'json'), stdout=P_AUTHENTICATED_TRUE_USER_ID_USR, check='auth_status'),
    C('auth.logout', 'auth.logout', invoke=lambda c: c.auth.logout(), expected_argv=('auth', 'logout', '--output', 'json'), stdout=P_AUTHENTICATED_FALSE_USER_ID_NU, check='auth_logout'),
    C('autopilots.list', 'autopilots.list', invoke=lambda c: c.autopilots.list(), expected_argv=('autopilot', 'list', '--output', 'json'), stdout=P_AUTOPILOTS_ID_AP_001_NAME_NI, check='nonempty'),
    C('autopilots.create', 'autopilots.create', invoke=lambda c: c.autopilots.create("AP"), expected_argv=('autopilot', 'create', '--name', 'AP', '--output', 'json'), stdout=P_ID_AP_001_NAME_AP_ENABLED_FAL),
    C('autopilots.get', 'autopilots.get', invoke=lambda c: c.autopilots.get("ap_001"), expected_argv=('autopilot', 'get', 'ap_001', '--output', 'json'), stdout=P_ID_AP_001_NAME_AP_ENABLED_FAL),
    C('autopilots.update', 'autopilots.update', invoke=lambda c: c.autopilots.update("ap_001", name="Renamed"), expected_argv=('autopilot', 'update', 'ap_001', '--name', 'Renamed', '--output', 'json'), stdout=P_ID_AP_001_NAME_AP_ENABLED_FAL),
    C('autopilots.delete', 'autopilots.delete', invoke=lambda c: c.autopilots.delete("ap_001"), expected_argv=('autopilot', 'delete', 'ap_001'), check='none'),
    C('autopilots.run', 'autopilots.run', invoke=lambda c: c.autopilots.run("ap_001"), expected_argv=('autopilot', 'run', 'ap_001', '--output', 'json'), stdout=P_ID_RUN_001_STATUS_COMPLETED),
    C('autopilots.history', 'autopilots.history', invoke=lambda c: c.autopilots.history("ap_001"), expected_argv=('autopilot', 'history', 'ap_001', '--output', 'json'), stdout=P_ID_RUN_001_STATUS_COMPLETED_2, check='nonempty'),
    C('autopilots.get_run', 'autopilots.get_run', invoke=lambda c: c.autopilots.get_run("run_001"), expected_argv=('autopilot', 'run', 'get', 'run_001', '--output', 'json'), stdout=P_ID_RUN_001_STATUS_COMPLETED),
    C('autopilots.triggers.list', 'autopilots.triggers.list', invoke=lambda c: c.autopilots.triggers.list("ap_001"), expected_argv=('autopilot', 'trigger', 'list', 'ap_001', '--output', 'json'), stdout=P_ID_TR_001_TYPE_WEBHOOK_CONFIG, check='nonempty'),
    C('autopilots.triggers.create', 'autopilots.triggers.create', invoke=lambda c: c.autopilots.triggers.create("ap_001", "webhook"), expected_argv=('autopilot', 'trigger', 'create', 'ap_001', '--type', 'webhook', '--output', 'json'), stdout=P_ID_TR_001_TYPE_WEBHOOK_CONFIG_2),
    C('autopilots.triggers.delete', 'autopilots.triggers.delete', invoke=lambda c: c.autopilots.triggers.delete("ap_001", "tr_001"), expected_argv=('autopilot', 'trigger', 'delete', 'ap_001', '--trigger-id', 'tr_001'), check='none'),
    C('configuration.show', 'configuration.show', invoke=lambda c: c.configuration.show(), expected_argv=('config', 'show'), stdout=P_WORKSPACE_WS_001_PROFILE_DEFAU),
    C('configuration.get', 'configuration.get', invoke=lambda c: c.configuration.get("key"), expected_argv=('config', 'get', 'key'), stdout=P_VALUE),
    C('configuration.set', 'configuration.set', invoke=lambda c: c.configuration.set("key", "val"), expected_argv=('config', 'set', 'key', 'val'), check='none'),
    C('daemon.status', 'daemon.status', invoke=lambda c: c.daemon.status(), expected_argv=('daemon', 'status', '--output', 'json'), stdout=P_RUNNING_TRUE_PID_12345_UPTIME_, check='daemon_status'),
    C('daemon.disk_usage', 'daemon.disk_usage', invoke=lambda c: c.daemon.disk_usage(), expected_argv=('daemon', 'disk-usage', '--output', 'json'), stdout=P_PATH_TMP_SIZE_BYTES_1024, check='nonempty'),
    C('daemon.start', 'daemon.start', invoke=lambda c: c.daemon.start(), expected_argv=('daemon', 'start')),
    C('daemon.stop', 'daemon.stop', invoke=lambda c: c.daemon.stop(), expected_argv=('daemon', 'stop', '--output', 'json'), stdout=P_RUNNING_FALSE),
    C('daemon.restart', 'daemon.restart', invoke=lambda c: c.daemon.restart(), expected_argv=('daemon', 'restart', '--output', 'json'), stdout=P_RUNNING_TRUE_PID_12345_UPTIME_),
    C('daemon.logs', 'daemon.logs', invoke=lambda c: c.daemon.logs(), expected_argv=('daemon', 'logs')),
    C('issues.list', 'issues.list', invoke=lambda c: c.issues.list(), expected_argv=('issue', 'list', '--output', 'json'), stdout=P_ISSUES_ID_ISS_001_TITLE_ISSU, check='nonempty'),
    C('issues.get', 'issues.get', invoke=lambda c: c.issues.get("iss_001"), expected_argv=('issue', 'get', 'iss_001', '--output', 'json'), stdout=P_ID_ISS_001_TITLE_TEST_ISSUE_DE),
    C('issues.create', 'issues.create', invoke=lambda c: c.issues.create(IssueCreateRequest(title="New issue")), expected_argv=('issue', 'create', '--title', 'New issue', '--output', 'json'), stdout=P_ID_ISS_001_TITLE_TEST_ISSUE_ST),
    C('issues.update', 'issues.update', invoke=lambda c: c.issues.update("iss_001", IssueUpdateRequest(title="Updated")), expected_argv=('issue', 'update', 'iss_001', '--title', 'Updated', '--output', 'json'), stdout=P_ID_ISS_001_TITLE_TEST_ISSUE_ST),
    C('issues.assign', 'issues.assign', invoke=lambda c: c.issues.assign(IssueAssignmentRequest(issue_id="iss_001", member_id="usr_001")), expected_argv=('issue', 'assign', 'iss_001', '--to-id', 'usr_001', '--output', 'json'), stdout=P_ID_ISS_001_TITLE_TEST_ISSUE_ST),
    C('issues.set_status', 'issues.set_status', invoke=lambda c: c.issues.set_status("iss_001", IssueStatus.done), expected_argv=('issue', 'status', 'iss_001', 'done', '--output', 'json'), stdout=P_ID_ISS_001_TITLE_TEST_ISSUE_ST_2, check='issue_done'),
    C('issues.deprioritize', 'issues.deprioritize', invoke=lambda c: c.issues.deprioritize("iss_001"), expected_argv=('issue', 'deprioritize', 'iss_001'), stdout=P_ISSUE_ISS_001_DEPRIORITIZED, check='deprioritized'),
    C('issues.reorder', 'issues.reorder', invoke=lambda c: c.issues.reorder(IssueReorderRequest(issue_id="iss_001", top=True)), expected_argv=('issue', 'reorder', 'iss_001', '--top', '--output', 'json'), stdout=P_ID_ISS_001_TITLE_TEST_ISSUE_ST),
    C('issues.search', 'issues.search', invoke=lambda c: c.issues.search("bug"), expected_argv=('issue', 'search', 'bug', '--output', 'json'), stdout=P_EMPTY),
    C('issues.children', 'issues.children', invoke=lambda c: c.issues.children("iss_001"), expected_argv=('issue', 'children', 'iss_001', '--output', 'json'), stdout=P_NAME_TODO_COUNT_1, check='nonempty'),
    C('issues.pull_requests', 'issues.pull_requests', invoke=lambda c: c.issues.pull_requests("iss_001"), expected_argv=('issue', 'pull-requests', 'iss_001', '--output', 'json'), stdout=P_URL_HTTPS_EXAMPLE_COM_PR_1, check='nonempty'),
    C('issues.runs', 'issues.runs', invoke=lambda c: c.issues.runs("iss_001"), expected_argv=('issue', 'runs', 'iss_001', '--output', 'json'), stdout=P_ID_RUN_001_STATUS_DONE, check='nonempty'),
    C('issues.run_messages', 'issues.run_messages', invoke=lambda c: c.issues.run_messages("iss_001", "run_001"), expected_argv=('issue', 'run-messages', 'iss_001', '--run-id', 'run_001', '--output', 'json'), stdout=P_ID_MSG_001_RUN_ID_RUN_001_ROL, check='nonempty'),
    C('issues.usage', 'issues.usage', invoke=lambda c: c.issues.usage("iss_001"), expected_argv=('issue', 'usage', 'iss_001', '--output', 'json'), stdout=P_TOTAL_RUNS_3),
    C('issues.rerun', 'issues.rerun', invoke=lambda c: c.issues.rerun("iss_001", "run_001"), expected_argv=('issue', 'rerun', 'iss_001', '--run-id', 'run_001'), check='none'),
    C('issues.cancel_task', 'issues.cancel_task', invoke=lambda c: c.issues.cancel_task("iss_001", "run_001"), expected_argv=('issue', 'cancel-task', 'iss_001', '--run-id', 'run_001'), check='none'),
    C('issues.comments.list', 'issues.comments.list', invoke=lambda c: c.issues.comments.list("iss_001"), expected_argv=('issue', 'comment', 'list', 'iss_001', '--output', 'json'), stdout=P_ID_CMT_001_CONTENT_HELLO, check='nonempty'),
    C('issues.comments.add', 'issues.comments.add', invoke=lambda c: c.issues.comments.add("iss_001", "hello"), expected_argv=('issue', 'comment', 'add', 'iss_001', '--content', 'hello', '--output', 'json'), stdout=P_ID_CMT_001_CONTENT_HELLO_2),
    C('issues.comments.reply', 'issues.comments.reply', invoke=lambda c: c.issues.comments.reply("iss_001", "th_001", "reply"), expected_argv=('issue', 'comment', 'add', 'iss_001', '--content', 'reply', '--parent', 'th_001', '--output', 'json'), stdout=P_ID_CMT_001_CONTENT_HELLO_2),
    C('issues.comments.delete', 'issues.comments.delete', invoke=lambda c: c.issues.comments.delete("cmt_001"), expected_argv=('issue', 'comment', 'delete', 'cmt_001'), check='none'),
    C('issues.comments.resolve', 'issues.comments.resolve', invoke=lambda c: c.issues.comments.resolve("th_001"), expected_argv=('issue', 'comment', 'resolve', 'th_001'), check='none'),
    C('issues.comments.unresolve', 'issues.comments.unresolve', invoke=lambda c: c.issues.comments.unresolve("th_001"), expected_argv=('issue', 'comment', 'unresolve', 'th_001'), check='none'),
    C('issues.labels.list', 'issues.labels.list', invoke=lambda c: c.issues.labels.list("iss_001"), expected_argv=('issue', 'label', 'list', 'iss_001', '--output', 'json'), stdout=P_ID_LBL_001_NAME_BUG_COLOR, check='labels'),
    C('issues.labels.add', 'issues.labels.add', invoke=lambda c: c.issues.labels.add("iss_001", "lbl_001"), expected_argv=('issue', 'label', 'add', 'iss_001', 'lbl_001', '--output', 'json'), stdout=P_ID_LBL_001_NAME_BUG_COLOR, check='labels'),
    C('issues.labels.remove', 'issues.labels.remove', invoke=lambda c: c.issues.labels.remove("iss_001", "lbl_001"), expected_argv=('issue', 'label', 'remove', 'iss_001', 'lbl_001', '--output', 'json'), stdout=P_EMPTY),
    C('issues.metadata.list', 'issues.metadata.list', invoke=lambda c: c.issues.metadata.list("iss_001"), expected_argv=('issue', 'metadata', 'list', 'iss_001', '--output', 'json'), stdout=P_KEY_FLAG_VALUE_TRUE, check='nonempty'),
    C('issues.metadata.get', 'issues.metadata.get', invoke=lambda c: c.issues.metadata.get("iss_001", "flag"), expected_argv=('issue', 'metadata', 'get', 'iss_001', '--key', 'flag', '--output', 'json'), stdout=P_KEY_FLAG_VALUE_TRUE_2),
    C('issues.metadata.set', 'issues.metadata.set', invoke=lambda c: c.issues.metadata.set("iss_001", "flag", True), expected_argv=('issue', 'metadata', 'set', 'iss_001', '--key', 'flag', '--value', 'true', '--type', 'boolean', '--output', 'json'), stdout=P_KEY_FLAG_VALUE_TRUE_2),
    C('issues.metadata.delete', 'issues.metadata.delete', invoke=lambda c: c.issues.metadata.delete("iss_001", "flag"), expected_argv=('issue', 'metadata', 'delete', 'iss_001', '--key', 'flag'), check='none'),
    C('issues.subscribers.list', 'issues.subscribers.list', invoke=lambda c: c.issues.subscribers.list("iss_001"), expected_argv=('issue', 'subscriber', 'list', 'iss_001', '--output', 'json'), stdout=P_ISSUE_ID_ISS_001_USER_TYPE_MEM, check='nonempty'),
    C('issues.subscribers.add', 'issues.subscribers.add', invoke=lambda c: c.issues.subscribers.add("iss_001", "usr_001"), expected_argv=('issue', 'subscriber', 'add', 'iss_001', '--user-id', 'usr_001'), stdout=P_ID_USR_001_NAME_USER, check='none'),
    C('issues.subscribers.remove', 'issues.subscribers.remove', invoke=lambda c: c.issues.subscribers.remove("iss_001", "usr_001"), expected_argv=('issue', 'subscriber', 'remove', 'iss_001', '--user-id', 'usr_001'), check='none'),
    C('labels.list', 'labels.list', invoke=lambda c: c.labels.list(), expected_argv=('label', 'list', '--output', 'json'), stdout=P_ID_LBL_001_NAME_BUG_COLOR_R, check='labels'),
    C('labels.get', 'labels.get', invoke=lambda c: c.labels.get("lbl_001"), expected_argv=('label', 'get', 'lbl_001', '--output', 'json'), stdout=P_ID_LBL_001_NAME_BUG_COLOR_F),
    C('labels.create', 'labels.create', invoke=lambda c: c.labels.create("bug"), expected_argv=('label', 'create', '--name', 'bug', '--output', 'json'), stdout=P_ID_LBL_001_NAME_BUG_COLOR_F),
    C('labels.update', 'labels.update', invoke=lambda c: c.labels.update("lbl_001", name="feature"), expected_argv=('label', 'update', 'lbl_001', '--name', 'feature', '--output', 'json'), stdout=P_ID_LBL_001_NAME_BUG_COLOR_F),
    C('labels.delete', 'labels.delete', invoke=lambda c: c.labels.delete("lbl_001"), expected_argv=('label', 'delete', 'lbl_001'), check='none'),
    C('maintenance.version', 'maintenance.version', invoke=lambda c: c.maintenance.version(), expected_argv=('version', '--output', 'json'), stdout=P_VERSION_0_1_0_COMMIT_ABC123_BU, check='maintenance_version'),
    C("maintenance.update", "maintenance.update", invoke=lambda c: c.maintenance.update(), expected_argv=("update",)),
    C('projects.list', 'projects.list', invoke=lambda c: c.projects.list(), expected_argv=('project', 'list', '--output', 'json'), stdout=P_ID_PR_001_TITLE_PROJECT_ALPHA, check='nonempty'),
    C('projects.get', 'projects.get', invoke=lambda c: c.projects.get("pr_001"), expected_argv=('project', 'get', 'pr_001', '--output', 'json'), stdout=P_ID_PR_001_TITLE_ALPHA_STATUS),
    C('projects.create', 'projects.create', invoke=lambda c: c.projects.create(ProjectCreateRequest(name="Alpha")), expected_argv=('project', 'create', '--title', 'Alpha', '--output', 'json'), stdout=P_ID_PR_001_TITLE_ALPHA_STATUS),
    C('projects.update', 'projects.update', invoke=lambda c: c.projects.update("pr_001", ProjectUpdateRequest(name="Beta")), expected_argv=('project', 'update', 'pr_001', '--title', 'Beta', '--output', 'json'), stdout=P_ID_PR_001_TITLE_ALPHA_STATUS),
    C('projects.delete', 'projects.delete', invoke=lambda c: c.projects.delete("pr_001"), expected_argv=('project', 'delete', 'pr_001'), check='none'),
    C('projects.set_status', 'projects.set_status', invoke=lambda c: c.projects.set_status("pr_001", ProjectStatus.completed), expected_argv=('project', 'status', 'pr_001', 'completed', '--output', 'json'), stdout=P_ID_PR_001_TITLE_PROJECT_ALPHA_2, check='project_completed'),
    C('repositories.list', 'repositories.list', invoke=lambda c: c.repositories.list(), expected_argv=('repo', 'list', '--output', 'json'), stdout=P_ID_RP_001_NAME_MAIN_REPO_URL, check='nonempty'),
    C('repositories.get', 'repositories.get', invoke=lambda c: c.repositories.get("repo_001"), expected_argv=('repo', 'get', 'repo_001', '--output', 'json'), stdout=P_ID_REPO_001_NAME_REPO),
    C('repositories.checkout', 'repositories.checkout', invoke=lambda c: c.repositories.checkout("repo_001", "main"), expected_argv=('repo', 'checkout', 'repo_001', '--branch', 'main', '--output', 'json'), stdout=P_PATH_TMP_REPO_BRANCH_MAIN_SUC),
    C('runtimes.list', 'runtimes.list', invoke=lambda c: c.runtimes.list(), expected_argv=('runtime', 'list', '--output', 'json'), stdout=P_ID_RT_001_NAME_PYTHON3_VERSIO, check='nonempty'),
    C('runtimes.get', 'runtimes.get', invoke=lambda c: c.runtimes.get("rt_001"), expected_argv=('runtime', 'get', 'rt_001', '--output', 'json'), stdout=P_ID_RT_001_NAME_PYTHON),
    C('setup.cloud', 'setup.cloud', invoke=lambda c: c.setup.cloud(), expected_argv=('setup', 'cloud'), stdout=P_CLOUD_SETUP_INITIATED),
    C('setup.self_host', 'setup.self_host', invoke=lambda c: c.setup.self_host("https://example.com"), expected_argv=('setup', 'self-host', '--url', 'https://example.com')),
    C('skills.list', 'skills.list', invoke=lambda c: c.skills.list(), expected_argv=('skill', 'list', '--output', 'json'), stdout=P_ID_SK_001_NAME_PYTHON_FILE_CO, check='nonempty'),
    C('skills.get', 'skills.get', invoke=lambda c: c.skills.get("sk_001"), expected_argv=('skill', 'get', 'sk_001', '--output', 'json'), stdout=P_ID_SK_001_NAME_SKILL_2),
    C('skills.create', 'skills.create', invoke=lambda c: c.skills.create(SkillCreateRequest(name="Skill")), expected_argv=('skill', 'create', '--name', 'Skill', '--output', 'json'), stdout=P_ID_SK_001_NAME_SKILL_2),
    C('skills.update', 'skills.update', invoke=lambda c: c.skills.update("sk_001", SkillUpdateRequest(name="Renamed")), expected_argv=('skill', 'update', 'sk_001', '--name', 'Renamed', '--output', 'json'), stdout=P_ID_SK_001_NAME_SKILL_2),
    C('skills.delete', 'skills.delete', invoke=lambda c: c.skills.delete("sk_001"), expected_argv=('skill', 'delete', 'sk_001'), check='none'),
    C('skills.import_from_url', 'skills.import_from_url', invoke=lambda c: c.skills.import_from_url("https://example.com/skill"), expected_argv=('skill', 'import', '--url', 'https://example.com/skill', '--output', 'json'), stdout=P_ID_SK_001_NAME_SKILL_2),
    C('skills.files.list', 'skills.files.list', invoke=lambda c: c.skills.files.list("sk_001"), expected_argv=('skill', 'file', 'list', 'sk_001', '--output', 'json'), stdout=P_ID_F_001_PATH_SKILL_MD_CONTEN, check='nonempty'),
    C('skills.files.upsert', 'skills.files.upsert', invoke=lambda c: c.skills.files.upsert("sk_001", "SKILL.md", "# Skill"), expected_argv=('skill', 'file', 'upsert', 'sk_001', '--path', 'SKILL.md', '--content', '# Skill', '--output', 'json'), stdout=P_ID_F_001_PATH_SKILL_MD_CONTENT),
    C('skills.files.delete', 'skills.files.delete', invoke=lambda c: c.skills.files.delete("sk_001", "f_001"), expected_argv=('skill', 'file', 'delete', 'sk_001', '--file-id', 'f_001'), check='none'),
    C('squads.list', 'squads.list', invoke=lambda c: c.squads.list(), expected_argv=('squad', 'list', '--output', 'json'), stdout=P_ID_SQ_001_NAME_TEAM_A_MEMBER, check='nonempty'),
    C('squads.get', 'squads.get', invoke=lambda c: c.squads.get("sq_001"), expected_argv=('squad', 'get', 'sq_001', '--output', 'json'), stdout=P_ID_SQ_001_NAME_SQUAD),
    C('users.list', 'users.list', invoke=lambda c: c.users.list(), expected_argv=('user', 'list', '--output', 'json'), stdout=P_ID_US_001_NAME_ALICE_ID_U, check='nonempty'),
    C('users.get', 'users.get', invoke=lambda c: c.users.get("usr_001"), expected_argv=('user', 'get', 'usr_001', '--output', 'json'), stdout=P_ID_USR_001_NAME_ALICE),
    C('workspaces.list', 'workspaces.list', invoke=lambda c: c.workspaces.list(), expected_argv=('workspace', 'list', '--output', 'json'), stdout=P_ID_WS_001_NAME_MAIN_WORKSPACE, check='nonempty'),
    C('workspaces.get', 'workspaces.get', invoke=lambda c: c.workspaces.get("ws_001"), expected_argv=('workspace', 'get', 'ws_001', '--output', 'json'), stdout=P_ID_WS_001_NAME_MAIN),
    C('workspaces.members', 'workspaces.members', invoke=lambda c: c.workspaces.members("ws_001"), expected_argv=('workspace', 'member', 'list', 'ws_001', '--output', 'json'), stdout=P_ID_USR_001_NAME_ALICE_2, check='nonempty'),
    C('workspaces.switch', 'workspaces.switch', invoke=lambda c: c.workspaces.switch("ws_001"), expected_argv=('workspace', 'switch', 'ws_001'), check='none'),
    C('workspaces.watch', 'workspaces.watch', invoke=lambda c: c.workspaces.watch("ws_001"), expected_argv=('workspace', 'watch', 'ws_001'), check='none'),
    C('workspaces.unwatch', 'workspaces.unwatch', invoke=lambda c: c.workspaces.unwatch("ws_001"), expected_argv=('workspace', 'unwatch', 'ws_001'), check='none'),
)

PROJECT_RESOURCE_COMMAND_CASES: tuple[CommandCase, ...] = (
    C('projects.resources.list', 'projects.resources.list', invoke=lambda c: c.projects.resources.list("pr_001"), expected_argv=('project', 'resource', 'list', 'pr_001', '--output', 'json'), stdout=P_PROJECT_RESOURCE_LIST, check='nonempty'),
    C('projects.resources.add_local_directory', 'projects.resources.add_local_directory', invoke=lambda c: c.projects.resources.add_local_directory("pr_001", ProjectResourceAddLocalDirectoryRequest(local_path="/tmp/sandbox", daemon_id="daemon-001")), expected_argv=('project', 'resource', 'add', 'pr_001', '--type', 'local_directory', '--local-path', _PR_LOCAL_DIR, '--daemon-id', 'daemon-001', '--output', 'json'), stdout=P_PROJECT_RESOURCE_RECORD),
    C('projects.resources.add_local_directory.label', 'projects.resources.add_local_directory', invoke=lambda c: c.projects.resources.add_local_directory("pr_001", ProjectResourceAddLocalDirectoryRequest(local_path="/tmp/sandbox", daemon_id="daemon-001", label="main")), expected_argv=('project', 'resource', 'add', 'pr_001', '--type', 'local_directory', '--local-path', _PR_LOCAL_DIR, '--daemon-id', 'daemon-001', '--ref-label', 'main', '--output', 'json'), stdout=P_PROJECT_RESOURCE_RECORD),
    C('projects.resources.update_local_directory', 'projects.resources.update_local_directory', invoke=lambda c: c.projects.resources.update_local_directory("pr_001", "res_001", ProjectResourceUpdateLocalDirectoryRequest(local_path="/tmp/sandbox")), expected_argv=('project', 'resource', 'update', 'pr_001', 'res_001', '--local-path', _PR_LOCAL_DIR, '--output', 'json'), stdout=P_PROJECT_RESOURCE_RECORD),
    C('projects.resources.remove', 'projects.resources.remove', invoke=lambda c: c.projects.resources.remove("pr_001", "res_001"), expected_argv=('project', 'resource', 'remove', 'pr_001', 'res_001'), check='none'),
)
