# fmt: off
from __future__ import annotations

import pathlib

_PR_LOCAL_DIR = str(pathlib.Path("/tmp/sandbox").resolve())
P_PROJECT_RESOURCE_RECORD = (
    f'{{"id":"res_001","project_id":"pr_001","resource_type":"local_directory",'
    f'"resource_ref":{{"local_path":"{_PR_LOCAL_DIR}","daemon_id":"daemon-001","label":"main"}}}}'
)
P_PROJECT_RESOURCE_LIST = f"[{P_PROJECT_RESOURCE_RECORD}]"

P_ID_AG_001_NAME_HELPER_SKILLS = "[{\"id\":\"ag_001\",\"name\":\"Helper\",\"skills\":[]}]"
P_ID_AG_001_NAME_HELPER_SKILLS_2 = "{\"id\":\"ag_001\",\"name\":\"Helper\",\"skills\":[]}"
P_ID_SK_001_NAME_SKILL = "[{\"id\":\"sk_001\",\"name\":\"Skill\"}]"
P_ID_TASK_001_STATUS_DONE_ISSUE = "[{\"id\":\"task_001\",\"status\":\"done\",\"issue_id\":\"iss_001\"}]"
P_ID_AT_001_FILENAME_FILE_TXT_U = "[{\"id\":\"at_001\",\"filename\":\"file.txt\",\"url\":\"https://example.com/file\"}]"
P_ID_ATT_001_FILENAME_FILE_TXT = "{\"id\":\"att_001\",\"filename\":\"file.txt\"}"
P_LOGIN_SUCCESSFUL = "Login successful"
P_AUTHENTICATED_TRUE_USER_ID_USR = "{\"authenticated\":true,\"user_id\":\"usr_001\",\"token_type\":\"bearer\"}"
P_AUTHENTICATED_FALSE_USER_ID_NU = "{\"authenticated\":false,\"user_id\":null,\"token_type\":null}"
P_AUTOPILOTS_ID_AP_001_NAME_NI = "{\"autopilots\":[{\"id\":\"ap_001\",\"name\":\"Nightly Build\",\"enabled\":true}],\"total\":1}"
P_ID_AP_001_NAME_AP_ENABLED_FAL = "{\"id\":\"ap_001\",\"name\":\"AP\",\"enabled\":false}"
P_ID_RUN_001_STATUS_COMPLETED = "{\"id\":\"run_001\",\"status\":\"completed\"}"
P_ID_RUN_001_STATUS_COMPLETED_2 = "[{\"id\":\"run_001\",\"status\":\"completed\"}]"
P_ID_TR_001_TYPE_WEBHOOK_CONFIG = "[{\"id\":\"tr_001\",\"type\":\"webhook\",\"config\":{}}]"
P_ID_TR_001_TYPE_WEBHOOK_CONFIG_2 = "{\"id\":\"tr_001\",\"type\":\"webhook\",\"config\":{}}"
P_WORKSPACE_WS_001_PROFILE_DEFAU = "workspace: ws_001\nprofile: default"
P_VALUE = "value"
P_RUNNING_TRUE_PID_12345_UPTIME_ = "{\"running\":true,\"pid\":12345,\"uptime\":3600.0}"
P_PATH_TMP_SIZE_BYTES_1024 = "[{\"path\":\"/tmp\",\"size_bytes\":1024}]"
P_RUNNING_FALSE = "{\"running\":false}"
P_ISSUES_ID_ISS_001_TITLE_ISSU = "{\"issues\":[{\"id\":\"iss_001\",\"title\":\"Issue one\",\"status\":\"todo\",\"priority\":\"high\"},{\"id\":\"iss_002\",\"title\":\"Issue two\",\"status\":\"in_progress\",\"priority\":\"medium\"}],\"total\":2,\"has_more\":false,\"offset\":0}"
P_ID_ISS_001_TITLE_TEST_ISSUE_DE = "{\"id\":\"iss_001\",\"title\":\"Test issue\",\"description\":\"A test issue description\",\"status\":\"todo\",\"priority\":\"high\",\"assignee\":{\"id\":\"usr_001\",\"name\":\"Test User\",\"type\":\"member\"},\"pull_requests\":[],\"children\":[],\"labels\":[{\"id\":\"lbl_001\",\"name\":\"bug\",\"color\":\"#ff0000\"}],\"metadata\":{},\"created_at\":\"2026-01-01T00:00:00Z\",\"updated_at\":\"2026-01-02T00:00:00Z\",\"unknown_field\":\"should be ignored by msgspec\"}"
P_ID_ISS_001_TITLE_TEST_ISSUE_ST = "{\"id\":\"iss_001\",\"title\":\"Test issue\",\"status\":\"todo\"}"
P_ID_ISS_001_TITLE_TEST_ISSUE_ST_2 = "{\"id\":\"iss_001\",\"title\":\"Test issue\",\"status\":\"done\",\"priority\":\"high\"}"
P_ISSUE_ISS_001_DEPRIORITIZED = "Issue iss_001 deprioritized\n"
P_EMPTY = "[]"
P_NAME_TODO_COUNT_1 = "[{\"name\":\"todo\",\"count\":1}]"
P_URL_HTTPS_EXAMPLE_COM_PR_1 = "[{\"url\":\"https://example.com/pr/1\"}]"
P_ID_RUN_001_STATUS_DONE = "[{\"id\":\"run_001\",\"status\":\"done\"}]"
P_ID_MSG_001_RUN_ID_RUN_001_ROL = "[{\"id\":\"msg_001\",\"run_id\":\"run_001\",\"role\":\"assistant\",\"content\":\"hi\"}]"
P_TOTAL_RUNS_3 = "{\"total_runs\":3}"
P_ID_CMT_001_CONTENT_HELLO = "[{\"id\":\"cmt_001\",\"content\":\"hello\"}]"
P_ID_CMT_001_CONTENT_HELLO_2 = "{\"id\":\"cmt_001\",\"content\":\"hello\"}"
P_ID_LBL_001_NAME_BUG_COLOR = "[{\"id\":\"lbl_001\",\"name\":\"bug\",\"color\":\"#ff0000\"}]"
P_KEY_FLAG_VALUE_TRUE = "[{\"key\":\"flag\",\"value\":true}]"
P_KEY_FLAG_VALUE_TRUE_2 = "{\"key\":\"flag\",\"value\":true}"
P_ISSUE_ID_ISS_001_USER_TYPE_MEM = "[{\"issue_id\":\"iss_001\",\"user_type\":\"member\",\"user_id\":\"usr_001\",\"reason\":\"manual\",\"created_at\":\"2026-01-01T00:00:00Z\"}]"
P_ID_USR_001_NAME_USER = "{\"id\":\"usr_001\",\"name\":\"User\"}"
P_ID_LBL_001_NAME_BUG_COLOR_R = "[{\"id\":\"lbl_001\",\"name\":\"bug\",\"color\":\"red\"},{\"id\":\"lbl_002\",\"name\":\"feature\",\"color\":null}]"
P_ID_LBL_001_NAME_BUG_COLOR_F = "{\"id\":\"lbl_001\",\"name\":\"bug\",\"color\":\"#ff0000\"}"
P_VERSION_0_1_0_COMMIT_ABC123_BU = "{\"version\":\"0.1.0\",\"commit\":\"abc123\",\"buildDate\":\"2026-01-01\",\"goVersion\":\"go1.22\",\"os\":\"linux\",\"arch\":\"amd64\"}"
P_ID_PR_001_TITLE_PROJECT_ALPHA = "[{\"id\":\"pr_001\",\"title\":\"Project Alpha\",\"description\":\"First project\",\"status\":\"in_progress\"},{\"id\":\"pr_002\",\"title\":\"Project Beta\",\"description\":null,\"status\":\"planned\"}]"
P_ID_PR_001_TITLE_ALPHA_STATUS = "{\"id\":\"pr_001\",\"title\":\"Alpha\",\"status\":\"planned\"}"
P_ID_PR_001_TITLE_PROJECT_ALPHA_2 = "{\"id\":\"pr_001\",\"title\":\"Project Alpha\",\"description\":\"First project\",\"status\":\"completed\"}"
P_ID_RP_001_NAME_MAIN_REPO_URL = "[{\"id\":\"rp_001\",\"name\":\"main-repo\",\"url\":\"https://example.com/repo\"}]"
P_ID_REPO_001_NAME_REPO = "{\"id\":\"repo_001\",\"name\":\"repo\"}"
P_PATH_TMP_REPO_BRANCH_MAIN_SUC = "{\"path\":\"/tmp/repo\",\"branch\":\"main\",\"success\":true}"
P_ID_RT_001_NAME_PYTHON3_VERSIO = "[{\"id\":\"rt_001\",\"name\":\"python3\",\"version\":\"3.12\"}]"
P_ID_RT_001_NAME_PYTHON = "{\"id\":\"rt_001\",\"name\":\"python\"}"
P_CLOUD_SETUP_INITIATED = "Cloud setup initiated"
P_ID_SK_001_NAME_PYTHON_FILE_CO = "[{\"id\":\"sk_001\",\"name\":\"Python\",\"file_count\":3}]"
P_ID_SK_001_NAME_SKILL_2 = "{\"id\":\"sk_001\",\"name\":\"Skill\"}"
P_ID_F_001_PATH_SKILL_MD_CONTEN = "[{\"id\":\"f_001\",\"path\":\"SKILL.md\",\"content\":\"# Skill\"}]"
P_ID_F_001_PATH_SKILL_MD_CONTENT = "{\"id\":\"f_001\",\"path\":\"SKILL.md\",\"content\":\"# Skill\"}"
P_ID_SQ_001_NAME_TEAM_A_MEMBER = "[{\"id\":\"sq_001\",\"name\":\"Team A\",\"member_count\":5}]"
P_ID_SQ_001_NAME_SQUAD = "{\"id\":\"sq_001\",\"name\":\"Squad\"}"
P_ID_US_001_NAME_ALICE_ID_U = "[{\"id\":\"us_001\",\"name\":\"Alice\"},{\"id\":\"us_002\",\"name\":\"Bob\"}]"
P_ID_USR_001_NAME_ALICE = "{\"id\":\"usr_001\",\"name\":\"Alice\"}"
P_ID_WS_001_NAME_MAIN_WORKSPACE = "[{\"id\":\"ws_001\",\"name\":\"Main Workspace\",\"description\":\"The main workspace\"},{\"id\":\"ws_002\",\"name\":\"Dev Workspace\",\"description\":null}]"
P_ID_WS_001_NAME_MAIN = "{\"id\":\"ws_001\",\"name\":\"Main\"}"
P_ID_USR_001_NAME_ALICE_2 = "[{\"id\":\"usr_001\",\"name\":\"Alice\"}]"
